In [1]:
import numpy as np

In [ ]:
! pip install nltk

In [5]:
import nltk

In [36]:
nltk.download()

showing info https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/index.xml


True

In [6]:
nltk.download('brown')

[nltk_data] Downloading package brown to
[nltk_data]     /Users/mohituniyal/nltk_data...
[nltk_data]   Unzipping corpora/brown.zip.


True

In [7]:
from nltk.corpus import brown

In [8]:
brown.categories()

['adventure',
 'belles_lettres',
 'editorial',
 'fiction',
 'government',
 'hobbies',
 'humor',
 'learned',
 'lore',
 'mystery',
 'news',
 'religion',
 'reviews',
 'romance',
 'science_fiction']

In [28]:
sentences = brown.sents(categories='science_fiction')

In [29]:
" ".join(sentences[1])

"Self's integrity was and is and ever had been ."

In [34]:
words =brown.words(categories="mystery")

In [35]:
words[:30]

['There',
 'were',
 'thirty-eight',
 'patients',
 'on',
 'the',
 'bus',
 'the',
 'morning',
 'I',
 'left',
 'for',
 'Hanover',
 ',',
 'most',
 'of',
 'them',
 'disturbed',
 'and',
 'hallucinating',
 '.',
 'An',
 'interne',
 ',',
 'a',
 'nurse',
 'and',
 'two',
 'attendants',
 'were']

## Basic NLP Pipeline
* Data Collection
* Tokenization, stopword removal, stemming
* Building a Common vocabulary
* Vectorize the documents
* Perform Classification

## Tokenization

In [40]:
nltk.download('punkt')

[nltk_data] Downloading package punkt to
[nltk_data]     /Users/mohituniyal/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [37]:
from nltk.tokenize import word_tokenize, sent_tokenize

In [38]:
s = "Dog is running on the grass"

In [41]:
word_tokenize(s)

['Dog', 'is', 'running', 'on', 'the', 'grass']

In [42]:
sen = "Dog is running on the grass. Movie was asweosme. weather is good"
sent_tokenize(sen)

['Dog is running on the grass.', 'Movie was asweosme.', 'weather is good']

## Stopwords

In [43]:
nltk.download("stopwords")

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/mohituniyal/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [44]:
from nltk.corpus import stopwords

In [46]:
sw = stopwords.words("english")

In [50]:
len(sw)

179

In [53]:
[w for w in word_tokenize(s) if w not in sw]

['Dog', 'running', 'grass']

## Stemming / Lemmatizing

In [73]:
from nltk.stem import PorterStemmer, SnowballStemmer, WordNetLemmatizer

In [74]:
ps = PorterStemmer()
ss = SnowballStemmer('english')
wnl = WordNetLemmatizer()

In [70]:
ps.stem("jumps")

'jump'

In [71]:
ps.stem("google")

'googl'

In [72]:
ss.stem("jump")

'jump'

In [76]:
# wnl.lemmatize("better")

In [107]:
def filter_words(s):
    return [ps.stem(w) for w in s if w not in sw]

In [78]:
filter_words(s)

['dog', 'run', 'grass']

In [79]:
s = "Dog is running , 1,,2,3, $^#&( *( cat is also running .. ))"

In [80]:
from nltk.tokenize import RegexpTokenizer

In [83]:
tokenizer = RegexpTokenizer("[a-zA-Z]+")

In [84]:
tokenizer.tokenize(s)

['Dog', 'is', 'running', 'cat', 'is', 'also', 'running']

## Building Common Vocabulary

In [108]:
def my_tokenizer(s):
    s = tokenizer.tokenize(s)
    return filter_words(s)

In [109]:
corpus= ["indian cricket team will win World Cup",
        "We will win next Lok Sabha Election, says Indian PM",
        "Raazi is an exciting Indian spy movie based on real incident",
        "APJ Won hearts of many Indians."]

In [110]:
from sklearn.feature_extraction.text import CountVectorizer

In [160]:
cv = CountVectorizer(tokenizer=my_tokenizer, ngram_range=(1,2), max_features=30)

In [161]:
cv.fit(corpus)

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=30, min_df=1,
                ngram_range=(1, 2), preprocessor=None, stop_words=None,
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=<function my_tokenizer at 0x1a311920e0>,
                vocabulary=None)

In [162]:
len(cv.vocabulary_)

30

In [163]:
vc = cv.transform(["I am an Indian"])

In [164]:
vc.toarray()

array([[0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0]])

In [165]:
vc = cv.transform(corpus).toarray()

In [166]:
vc

array([[0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 1, 1, 1, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1,
        1, 0, 0, 0, 0, 1, 1, 0],
       [0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0,
        0, 1, 1, 0, 0, 0, 0, 0],
       [1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0]])

In [167]:
vc = cv.fit_transform(corpus)

In [168]:
print(cv.vocabulary_)

{'indian': 7, 'cricket': 4, 'team': 25, 'win': 27, 'cup': 6, 'cricket team': 5, 'team win': 26, 'win world': 29, 'next': 12, 'sabha': 19, 'say': 21, 'pm': 14, 'win next': 28, 'next lok': 13, 'sabha elect': 20, 'say indian': 22, 'raazi': 15, 'spi': 23, 'movi': 10, 'base': 2, 'real': 17, 'raazi excit': 16, 'spi movi': 24, 'movi base': 11, 'base real': 3, 'real incid': 18, 'apj': 0, 'mani': 8, 'apj heart': 1, 'mani indian': 9}


In [138]:
cv.transform(["US President"]).toarray()

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [139]:
vc[1]

<1x22 sparse matrix of type '<class 'numpy.int64'>'
	with 8 stored elements in Compressed Sparse Row format>

In [140]:
cv.inverse_transform(vc[1])

[array(['indian', 'win', 'next', 'lok', 'sabha', 'elect', 'say', 'pm'],
       dtype='<U7')]

In [141]:
print(cv.get_feature_names())

['apj', 'base', 'cricket', 'cup', 'elect', 'excit', 'heart', 'incid', 'indian', 'lok', 'mani', 'movi', 'next', 'pm', 'raazi', 'real', 'sabha', 'say', 'spi', 'team', 'win', 'world']


In [169]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [170]:
tfidf = TfidfVectorizer(tokenizer=my_tokenizer)

In [173]:
vc_ifidf = tfidf.fit_transform(corpus).toarray()

In [174]:
vc_ifidf

array([[0.        , 0.        , 0.45203489, 0.45203489, 0.        ,
        0.        , 0.        , 0.        , 0.23589056, 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.45203489,
        0.3563895 , 0.45203489],
       [0.        , 0.        , 0.        , 0.        , 0.38086157,
        0.        , 0.        , 0.        , 0.19874937, 0.38086157,
        0.        , 0.        , 0.38086157, 0.38086157, 0.        ,
        0.        , 0.38086157, 0.38086157, 0.        , 0.        ,
        0.30027564, 0.        ],
       [0.        , 0.37082034, 0.        , 0.        , 0.        ,
        0.37082034, 0.        , 0.37082034, 0.19350944, 0.        ,
        0.        , 0.37082034, 0.        , 0.        , 0.37082034,
        0.37082034, 0.        , 0.        , 0.37082034, 0.        ,
        0.        , 0.        ],
       [0.55280532, 0.        , 0.        , 0.        , 0.        ,
        0.       

In [178]:
tfidf.transform(["PM Modi is best"]).toarray()

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
        0., 0., 0., 0., 0., 0.]])