In [1]:
! pip install numpy

In [5]:
import numpy as np

In [7]:
l = [1,2,3,5,7,9]

In [9]:
new_l = []
for i in l:
    new_l.append(i+5)

In [10]:
new_l

[6, 7, 8, 10, 12, 14]

In [11]:
type(l)

list

In [18]:
arr = np.array(l)
arr2 = np.array([9,8,7,6,5,4])

In [23]:
print(arr + arr2)
print(arr - arr2)
print(arr//arr2)

[10 10 10 11 12 13]
[-8 -6 -4 -1  2  5]
[0 0 0 0 1 2]


In [24]:
arr*5

array([ 5, 10, 15, 25, 35, 45])

In [27]:
arr.shape

(6,)

In [28]:
arr_2d = np.array([[1,2], 
                   [3,4]])

In [29]:
arr_2d

array([[1, 2],
       [3, 4]])

In [33]:
arr_2d.shape

(2, 2)

In [40]:
arr_2d

array([[1, 2],
       [3, 4]])

In [51]:
arr_2d[: , 1 ].shape

(2,)

In [52]:
arr1 = np.array([
                [1],
                [2],
                [3],
                [4]
                ])

In [53]:
arr1.shape

(4, 1)

In [54]:
arr1

array([[1],
       [2],
       [3],
       [4]])

In [57]:
arr1.reshape((4,1))

array([[1],
       [2],
       [3],
       [4]])

In [60]:
arr

array([1, 2, 3, 5, 7, 9])

In [59]:
arr.shape

(6,)

In [64]:
arr  = arr.reshape((1,6))

In [65]:
arr.shape

(1, 6)

In [68]:
arr.shape

(1, 6)

In [74]:
arr.reshape((2,-1))

array([[1, 2, 3],
       [5, 7, 9]])

In [75]:
arr.dtype

dtype('int64')

In [80]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [84]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [89]:
np.full((5,5), 8)

array([[8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8]])

In [86]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Random Numbers

In [267]:
np.random.randint(10, 100, (4,5))

array([[66, 56, 66, 48, 65],
       [13, 32, 44, 97, 85],
       [60, 98, 27, 90, 59],
       [23, 55, 91, 59, 93]])

In [249]:
r = np.random.rand(3,5,6)

In [259]:
print(r[0][1:3, 1:3 ])

[[0.10664598 0.80324505 0.09240718 0.70363313 0.89690094 0.48670376]
 [0.73303746 0.89969354 0.27692582 0.46443047 0.57787745 0.60822079]
 [0.10406266 0.63302715 0.61522365 0.60454931 0.52963618 0.51762987]
 [0.26490685 0.59879294 0.16238463 0.21142404 0.89752952 0.73278931]
 [0.33919288 0.31626074 0.17581207 0.61331324 0.4561101  0.91299985]]


In [279]:
print(r[0][1:3])

[[0.73303746 0.89969354 0.27692582 0.46443047 0.57787745 0.60822079]
 [0.10406266 0.63302715 0.61522365 0.60454931 0.52963618 0.51762987]]


In [281]:
print(r[0][1:3])

[[0.73303746 0.89969354 0.27692582 0.46443047 0.57787745 0.60822079]
 [0.10406266 0.63302715 0.61522365 0.60454931 0.52963618 0.51762987]]


In [290]:
ra = np.random.randn(100)

In [291]:
np.mean(ra)

0.023021381537856184

In [292]:
np.std(ra)

1.0066055224766561

In [301]:
std = 10
mean = 70

In [302]:
marks = ra*std + mean

In [303]:
marks

array([59.21502473, 58.9469457 , 83.3614422 , 53.7582239 , 64.72925706,
       85.82592237, 72.86173209, 70.60525511, 66.11267964, 80.42077677,
       58.46422127, 58.27241348, 59.36373032, 71.45886076, 70.74955517,
       63.88546492, 65.96644415, 63.0206921 , 64.72449962, 77.44209023,
       54.3510658 , 81.52506494, 83.92535181, 79.18013353, 83.10365738,
       53.42744363, 71.75077239, 70.07899657, 72.89828962, 77.39024776,
       70.55545712, 75.77343307, 59.90442242, 52.62314301, 64.62918088,
       69.98887123, 68.49730659, 76.30793365, 83.89205283, 79.45530198,
       62.91708721, 69.04686601, 88.90545508, 71.58169476, 52.10494306,
       72.1244195 , 73.25360427, 69.09963978, 67.02888291, 75.38445254,
       63.51650574, 66.841115  , 81.78864047, 72.70885546, 84.85852949,
       71.49487612, 63.76864332, 88.94988524, 67.35252757, 78.65686573,
       53.41131932, 53.59163835, 54.20797365, 63.14040465, 72.82524089,
       64.201355  , 77.20071828, 65.65376049, 59.18003099, 73.37

In [310]:
np.sqrt((1/100)* np.sum((marks - np.mean(marks))**2))

10.066055224766561

# Boradcasting

In [351]:
arr = np.random.randint(10,100, (3,3))

In [352]:
arr

array([[45, 15, 48],
       [59, 76, 50],
       [28, 62, 26]])

In [340]:
arr2 = np.array([[1,2,3]])

In [341]:
arr

array([[98, 70, 90],
       [98, 74, 69],
       [59, 26, 96]])

In [342]:
arr2

array([[1, 2, 3]])

In [343]:
arr+ arr2

array([[99, 72, 93],
       [99, 76, 72],
       [60, 28, 99]])

# Matrix Operations

In [320]:
arr = np.random.randint(10,100, (3,3))

In [321]:
arr2= np.random.randint(10,100, (2,3))

In [323]:
np.dot(arr2, arr)

array([[10074,  4128,  9011],
       [15547,  8003,  9510]])

In [324]:
arr2.dot(arr)

array([[10074,  4128,  9011],
       [15547,  8003,  9510]])

In [333]:
arr

array([[66, 19, 29],
       [69, 57, 13],
       [62, 25, 76]])

In [335]:
np.sum(arr, axis =1)

array([114, 139, 163])

In [353]:
def dist(v1, v2):
    return np.sqrt(np.sum((v1-v2)**2))

In [357]:
dist(np.array([5, 2]), np.array([4, 1]))

1.4142135623730951

In [ ]:
np.median()

In [358]:
np.mean

<function numpy.mean(a, axis=None, dtype=None, out=None, keepdims=<no value>)>

In [360]:
np.sin(360)

0.9589157234143065

In [361]:
np.log(10)


2.302585092994046

In [362]:
np.exp(2)

7.38905609893065

In [363]:
np.abs(-1)

1

In [367]:
np.unique([1, 9 ,2,2, 1, 1, 3, 3], return_counts=True)

(array([1, 2, 3, 9]), array([3, 2, 2, 1]))